update

diff --git a/offline_install.diff b/offline_install.diff
--- a/offline_install.diff
+++ b/offline_install.diff
@@ -1,11 +1,18 @@
 diff --git a/tools/install.sh b/tools/install.sh
-index a6538f9d..04fa80c8 100755
+index f4ef16a0..e23cb54a 100755
 --- a/tools/install.sh
 +++ b/tools/install.sh
-@@ -264,40 +264,8 @@ setup_ohmyzsh() {
-   # that this will be ignored under Cygwin by default, as Windows ACLs take
-   # precedence over umasks except for filesystems mounted with option "noacl".
-   umask g-w,o-w
+@@ -269,53 +269,6 @@ setup_color() {
+   FMT_RESET=$(printf '\033[0m')
+ }
+ 
+-setup_ohmyzsh() {
+-  # Prevent the cloned repository from having insecure permissions. Failing to do
+-  # so causes compinit() calls to fail with "command not found: compdef" errors
+-  # for users with insecure umasks (e.g., "002", allowing group writability). Note
+-  # that this will be ignored under Cygwin by default, as Windows ACLs take
+-  # precedence over umasks except for filesystems mounted with option "noacl".
+-  umask g-w,o-w
 -
 -  echo "${FMT_BLUE}Cloning Oh My Zsh...${FMT_RESET}"
 -
@@ -40,8 +47,47 @@ index a6538f9d..04fa80c8 100755
 -    fmt_error "git clone of oh-my-zsh repo failed"
 -    exit 1
 -  }
-+  cp -ra "$(dirname "$0")"/.. $ZSH
-+  rm -rf $ZSH/.git
-   # Exit installation directory
-   cd -
+-  # Exit installation directory
+-  cd -
+-
+-  echo
+-}
+-
+ setup_zshrc() {
+   # Keep most recent old .zshrc at .zshrc.pre-oh-my-zsh, and older ones
+   # with datestamp of installation that moved them aside, so we never actually
+@@ -501,34 +454,11 @@ main() {
+     exit 1
+   fi
+ 
+-  if [ -d "$ZSH" ]; then
+-    echo "${FMT_YELLOW}The \$ZSH folder already exists ($ZSH).${FMT_RESET}"
+-    if [ "$custom_zsh" = yes ]; then
+-      cat <<EOF
+-
+-You ran the installer with the \$ZSH setting or the \$ZSH variable is
+-exported. You have 3 options:
+-
+-1. Unset the ZSH variable when calling the installer:
+-   $(fmt_code "ZSH= sh install.sh")
+-2. Install Oh My Zsh to a directory that doesn't exist yet:
+-   $(fmt_code "ZSH=path/to/new/ohmyzsh/folder sh install.sh")
+-3. (Caution) If the folder doesn't contain important information,
+-   you can just remove it with $(fmt_code "rm -r $ZSH")
+-
+-EOF
+-    else
+-      echo "You'll need to remove it if you want to reinstall."
+-    fi
+-    exit 1
+-  fi
+-
+   # Create ZDOTDIR folder structure if it doesn't exist
+   if [ -n "$ZDOTDIR" ]; then
+     mkdir -p "$ZDOTDIR"
+   fi
+ 
+-  setup_ohmyzsh
+   setup_zshrc
+   setup_shell
  
